#pragma once

// BG (collision) attributes: what a field unit's ground is. dFdBase_c::getBgAttr returns a unit's
// attribute. The names are the game's own, from its attribute table (0x86 entries of 0x29 bytes at
// 804A55A8, name at +0x14; no code reads the names). Each entry's flag bytes +0x27 / +0x28 decide
// what the per-unit BG queries answer; see notes/bg_attributes.txt for the table.

enum {
    BG_ATTR_NONE = 0x00,
    BG_ATTR_ATTRW = 0x01,
    BG_ATTR_OBJ = 0x02,
    BG_ATTR_STR_COL = 0x03,
    BG_ATTR_STR_ENT = 0x04,
    BG_ATTR_STR_INS = 0x05,
    BG_ATTR_STR_DEL = 0x06,
    BG_ATTR_STR_ENT_TO_RU = 0x07,
    BG_ATTR_STR_ENT_TO_LU = 0x08,
    BG_ATTR_NEXT0 = 0x09,
    BG_ATTR_NEXT1 = 0x0A,
    BG_ATTR_NEXT2 = 0x0B,
    BG_ATTR_NEXT3 = 0x0C,
    BG_ATTR_NEXT4 = 0x0D,
    BG_ATTR_NEXT5 = 0x0E,
    BG_ATTR_NEXT6 = 0x0F,
    BG_ATTR_WALL = 0x10,
    BG_ATTR_CHANGE = 0x11,
    BG_ATTR_WATER = 0x12,
    BG_ATTR_STONE = 0x13,
    BG_ATTR_FLOOR = 0x14,
    BG_ATTR_WOOD = 0x15,
    BG_ATTR_SOIL = 0x16,
    BG_ATTR_SAND = 0x17,
    BG_ATTR_SEA = 0x18,
    BG_ATTR_BRIDGE = 0x19,
    BG_ATTR_WAVE = 0x1A,
    BG_ATTR_RIVER_N = 0x1B,
    BG_ATTR_RIVER_NW = 0x1C,
    BG_ATTR_RIVER_W = 0x1D,
    BG_ATTR_RIVER_SW = 0x1E,
    BG_ATTR_RIVER_S = 0x1F,
    BG_ATTR_RIVER_SE = 0x20,
    BG_ATTR_RIVER_E = 0x21,
    BG_ATTR_RIVER_NE = 0x22,
    BG_ATTR_SOILX = 0x23,
    BG_ATTR_WAVE_S = 0x24,
    BG_ATTR_WAVE_SE2 = 0x25,
    BG_ATTR_WAVE_SW2 = 0x26,
    BG_ATTR_WAVE_SE = 0x27,
    BG_ATTR_WAVE_SW = 0x28,
    BG_ATTR_SOIL_NW_SEA_SE = 0x29,
    BG_ATTR_SOIL_NE_SEA_SW = 0x2A,
    BG_ATTR_WATER_NW_SOILX_SE = 0x2B,
    BG_ATTR_WATER_SW_SOILX_NE = 0x2C,
    BG_ATTR_WATER_SE_SOILX_NW = 0x2D,
    BG_ATTR_WATER_NE_SOILX_SW = 0x2E,
    BG_ATTR_BR_RIVER_N = 0x2F,
    BG_ATTR_BR_RIVER_W = 0x30,
    BG_ATTR_BR_RIVER_S = 0x31,
    BG_ATTR_BR_RIVER_E = 0x32,
    BG_ATTR_BR_RIVER_NW = 0x33,
    BG_ATTR_BR_RIVER_SW = 0x34,
    BG_ATTR_BR_RIVER_SE = 0x35,
    BG_ATTR_BR_RIVER_NE = 0x36,
    BG_ATTR_BR_NW_SO_SE = 0x37,
    BG_ATTR_BR_SW_SO_NE = 0x38,
    BG_ATTR_BR_SE_SO_NW = 0x39,
    BG_ATTR_BR_NE_SO_SW = 0x3A,
    BG_ATTR_BR_NW_RIVER_NW = 0x3B,
    BG_ATTR_BR_SW_RIVER_SW = 0x3C,
    BG_ATTR_BR_SE_RIVER_SE = 0x3D,
    BG_ATTR_BR_NE_RIVER_NE = 0x3E,
    BG_ATTR_BR_NW_RIVER_SE = 0x3F,
    BG_ATTR_BR_SW_RIVER_NE = 0x40,
    BG_ATTR_BR_SE_RIVER_NW = 0x41,
    BG_ATTR_BR_NE_RIVER_SW = 0x42,
    BG_ATTR_BR_NW_RIVER_N = 0x43,
    BG_ATTR_BR_SW_RIVER_S = 0x44,
    BG_ATTR_BR_SE_RIVER_S = 0x45,
    BG_ATTR_BR_NE_RIVER_N = 0x46,
    BG_ATTR_BR_NW_RIVER_S = 0x47,
    BG_ATTR_BR_SW_RIVER_N = 0x48,
    BG_ATTR_BR_SE_RIVER_N = 0x49,
    BG_ATTR_BR_NE_RIVER_S = 0x4A,
    BG_ATTR_BR_NW_RIVER_W = 0x4B,
    BG_ATTR_BR_SW_RIVER_W = 0x4C,
    BG_ATTR_BR_SE_RIVER_E = 0x4D,
    BG_ATTR_BR_NE_RIVER_E = 0x4E,
    BG_ATTR_BR_NW_RIVER_E = 0x4F,
    BG_ATTR_BR_SW_RIVER_E = 0x50,
    BG_ATTR_BR_SE_RIVER_W = 0x51,
    BG_ATTR_BR_NE_RIVER_W = 0x52,
    BG_ATTR_STONE_NW = 0x53,
    BG_ATTR_STONE_SW = 0x54,
    BG_ATTR_STONE_SE = 0x55,
    BG_ATTR_STONE_NE = 0x56,
    BG_ATTR_CLIFF_N = 0x57,
    BG_ATTR_CLIFF_W = 0x58,
    BG_ATTR_CLIFF_S = 0x59,
    BG_ATTR_CLIFF_E = 0x5A,
    BG_ATTR_CLIFF_NW = 0x5B,
    BG_ATTR_CLIFF_NE = 0x5C,
    BG_ATTR_CLIFF_SW = 0x5D,
    BG_ATTR_CLIFF_SE = 0x5E,
    BG_ATTR_CLIFF_NW2 = 0x5F,
    BG_ATTR_CLIFF_NE2 = 0x60,
    BG_ATTR_CLIFF_SW2 = 0x61,
    BG_ATTR_CLIFF_SE2 = 0x62,
    BG_ATTR_SAND_SE = 0x63,
    BG_ATTR_SAND_SW = 0x64,
    BG_ATTR_STONE_BUS = 0x65,
    BG_ATTR_LIGHTHOUSE = 0x66,
    BG_ATTR_TAILOR = 0x67,
    BG_ATTR_IRON = 0x68,
    BG_ATTR_MUSHIRO = 0x69,
    BG_ATTR_INDOOR_SAND = 0x6A,
    BG_ATTR_CARPET = 0x6B,
    BG_ATTR_BR_RACCO_W = 0x6C,
    BG_ATTR_BR_RACCO_S = 0x6D,
    BG_ATTR_BR_RACCO_E = 0x6E,
    BG_ATTR_BR_RACCO_SW = 0x6F,
    BG_ATTR_BR_RACCO_SE = 0x70,
    BG_ATTR_COBBLE = 0x71,
    BG_ATTR_GOTO_RESET = 0x72,
    BG_ATTR_UFO = 0x73,
    BG_ATTR_INDOOR_SOIL = 0x74,
    BG_ATTR_INDOOR_GRASS = 0x75,
    BG_ATTR_FALL_S = 0x76,
    BG_ATTR_FALL_SW = 0x77,
    BG_ATTR_FALL_SE = 0x78,
    BG_ATTR_SOIL_SW_SEA_NE = 0x79,
    BG_ATTR_SOIL_SE_SEA_NW = 0x7A,
    BG_ATTR_SEA_SW = 0x7B,
    BG_ATTR_SEA_SE = 0x7C,
    BG_ATTR_TOWN = 0x7D,
    BG_ATTR_TOWN_NO_NPC = 0x7E,
    BG_ATTR_CARPET_NEXT0 = 0x7F,
    BG_ATTR_CARPET_NEXT1 = 0x80,
    BG_ATTR_CARPET_NEXT2 = 0x81,
    BG_ATTR_CARPET_NEXT3 = 0x82,
    BG_ATTR_CARPET_NEXT4 = 0x83,
    BG_ATTR_CARPET_NEXT5 = 0x84,
    BG_ATTR_CARPET_NEXT6 = 0x85,

    BG_ATTR_NUM = 0x86, // larger attributes always give a query's default
};

// The water kind of an attribute (+0x27 bits 6..7; dBGCF::getWaterKind, dBGCF::groundChk_c::mWater).
enum bgWater_e {
    BG_WATER_NONE = 0,
    BG_WATER_RIVER = 1, // RIVER_*, FALL_*
    BG_WATER_SEA = 2,   // SEA, SEA_SW / SE, WAVE, UFO
    BG_WATER_POND = 3   // WATER
};

// What digging an attribute gives (+0x27 bits 2..3; dBGCF::getDigType).
enum bgDig_e {
    BG_DIG_SOIL = 0,
    BG_DIG_SAND = 1,
    BG_DIG_OTHER = 2,
    BG_DIG_WATER = 3
};

// What grows on an attribute (+0x27 bits 4..5; dBGCF::getPlantType).
enum bgPlant_e {
    BG_PLANT_NONE = 0,
    BG_PLANT_SOILX = 1, // SOILX, the cliffs, sand
    BG_PLANT_SOIL = 2   // SOIL only: saplings grow
};
